---
apiVersion: v1
kind: Service
metadata:
  name: validating-webhook
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: imgctrl
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: imageio
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: imgctrl
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: imgctrl
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: imageio-external
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: imgctrl
  ports:
    - port: 8083
      targetPort: 8083
