{{- /*
Here we generate a self signed certificate to use if user has not provided us with one
through .Values.cert and .Values.key. Once this chart is installed we never change the
certificates.
*/}}
{{- $altNames := list ( printf "validating-webhook.%s.svc" .Release.Namespace ) }}
{{- $ca := genCA "imgctrl" 365 }}
{{- $cert := genSignedCert "imgctrl" nil $altNames 365 $ca }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "certs" ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: certs
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if $secret }}
  {{- toYaml $secret.data | nindent 2 }}
  {{- else }}
  tls.crt: {{ default $cert.Cert .Values.cert | b64enc }}
  tls.key: {{ default $cert.Key .Values.key | b64enc }}
  {{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: imgctrl
webhooks:
- name: image.shipwright.io
  rules:
  - apiGroups:
    - shipwright.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - images
    scope: Namespaced
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: validating-webhook
      path: "/image"
      port: 8080
    {{- if $secret }}
    caBundle: {{ (index $secret "data" "server.crt") }}
    {{- else }}
    caBundle: {{ default $cert.Cert .Values.cert | b64enc }}
    {{- end }}
  admissionReviewVersions:
  - v1
  sideEffects: None
  timeoutSeconds: 3
- name: imageimport.shipwright.io
  rules:
  - apiGroups:
    - shipwright.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - imageimports
    scope: Namespaced
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: validating-webhook
      path: "/imageimport"
      port: 8080
    {{- if $secret }}
    caBundle: {{ (index $secret "data" "server.crt") }}
    {{- else }}
    caBundle: {{ default $cert.Cert .Values.cert | b64enc }}
    {{- end }}
  admissionReviewVersions:
  - v1
  sideEffects: None
  timeoutSeconds: 3
